const mongoose = require('mongoose');

const DataSchema = mongoose.Schema({
    schoolParent:{
        type:String,
        require:true
    },
    name:{
        type:String,
        require:true
    },
    establishYear:{
        type:String,
        require:true
    },
    approximatlyStudent:{
        type:String,
        require:true
    },
    brand:{
        type:String,
        require:true
    },
    email:{
        type:String,
        require:true
    },
    principalName:{
        type:String,
        require:true
    },
    levelServiced:{
        type:String,
        require:true
    },
    address:{
        type:String,
        require:true
    },
    contactPerson1:{
        type:String,
        require:true
    },
    contactNumber1:{
        type:String,
        require:true
    },
    contactType1:{
        type:String,
        require:true
    },
    contactPerson2:{
        type:String,
        require:true
    },
    contactNumber2:{
        type:String,
        require:true
    },
    contactType2:{
        type:String,
        require:true
    },
    city:{
        type:String,
        require:true
    },
    Pincode:{
        type:String,
        require:true
    },
    numberClass:{
        type:String,
        require:true
    },
    boardType:{
        type:String,
        require:true
    }
});

module.exports = mongoose.model('Data',DataSchema);